version: '3.2'
services: 
  workspace:
    build:
      context: './'
    image: ${COMPOSE_PROJECT_NAME}-workspace
    container_name: '${COMPOSE_PROJECT_NAME}-workspace'
    volumes: 
      - ../:/${PROJECT_PATH}:cached
      - ./bashrc:/root/.bashrc
      - ${GOMODCACHE}/pkg/mod/:/go/pkg/mod/
      - ./git-credentials:/root/.git-credentials
    environment: 
      - ENV=/root/.bashrc
      - LOGGER_LEVEL=debug
      - MYSQL_HOST=172.18.0.62
      - SERVICE_ENV=dev
      - GOPROXY=http://172.18.0.177
      - CALL_SERVICE_ENV=test
      - RUN_MODE=dev
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=172.18.0.62
      # - MICRO_BROKER=kafka
      # - BROKER_ADDRESS=172.18.0.62:9092
    # ports: 
    #   - 80:80 
    working_dir: /${PROJECT_PATH}
    tty: true
    network_mode: host