version: '3.2'
networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 192.2.0.0/16
services: 
  workspace:
    build:
      context: './'
    image: ${COMPOSE_PROJECT_NAME}-workspace
    container_name: '${COMPOSE_PROJECT_NAME}-workspace'
    volumes: 
      - ../:/${COMPOSE_PROJECT_NAME}:cached
      - ./bashrc:/root/.bashrc
    environment: 
      - ENV=/root/.bashrc
    # ports: 
    #   - 80:80 
    working_dir: /${COMPOSE_PROJECT_NAME}
    tty: true
    networks: 
      - dev
